#!/bin/bash

status=$(lynx -source statusblog.locaweb.com.br | grep -A 10 "Email$" | cut -d " " -f5 | sed "1,9d" | sed 2d | tr A-Z a-z)

if [ "$status" == "operational" ]; then

# Está está ok

echo 1

else

# senão, está fora

echo 0

fi
